version: '3'
services:
  jupyter:
    build: .
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - JUPYTER_TOKEN=d4484563805c48c9b55f75eb8b28b3797c6757ad4871776d
    command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root
  tensorboard:
    build: .
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - "6006:6006"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: tensorboard --logdir=./tensorflow_logs --port=6006 --host 0.0.0.0
  bash:
    build: .
    working_dir: /code
    volumes:
      - .:/code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true # docker run -i
    tty: true        # docker run -t
